### ISSUE TITLE
老哥 能讲下原理吗 你这一个类加注解是如何处理的 编译的类在哪? kotlin代码看的优点头大

### ISSUE THREAD

**Issue by jingyc0305** [7hens/okbinder#1]

**Comment by 7hens** [comment]
那我大致说一下原理吧。

OKBinder 是一个进程间通信（IPC）方案。
不管是哪种 IPC 方案，都离不开 Binder。
而 Binder 间的数据通信则是依赖于 Parcel，通过观察 AIDL 生成的类就可以发现这一点。

**OkBinder 也是利用了 Parcel。**

先看服务端：

在新建一个 OkBinder 实例时，需要传入一个远程服务对象（remoteObject）。
而这个 remoteObject 要求继承一个被 `@OkBinder.Inteface` 注解的接口（这里举个例子，假设名为 RemoteInterface）。

OkBinder 会通过反射将 RemoteInterface 所有的方法都遍历并缓存起来，等待 onTransact 被调用的时候执行。（具体可以看 `OkBinder.onTransact` 方法）

再看客户端的调用：

`OkBinder.proxy` 实际返回了一个 RemoteInterface 的动态代理。
而每一个被代理的方法都调用了 `binder.transact` 方法，这对应了上面服务端的 `OkBinder.onTrasact` 方法，从而实现了跨进程通信。

**Comment by 7hens** [comment]
@jingyc0305 我把 OkBinder 用 java 重写了 😂

**Comment by sd3970566** [comment]
不是说多进程通信吗，怎么让他变成2个APP通信进程测试呢··

**Comment by 7hens** [comment]
@sd3970566 让两个 APP 都使用 OkBinder 就可以了。服务端 APP 使用 `OkBinder.create(remoteInterface)` 来提供远程接口，客户端 APP 使用 `OkBinder.proxy(IRemoteInterface.java, service)` 来得到这个接口。
