### ISSUE TITLE
关于okbinder的关键功能问题。

### ISSUE THREAD

**Issue by JayceKing** [7hens/okbinder#3]
1.支不支持多服务端多客户端并用
2.消息传递是串行的还是并行的？如果是串行的能否新增并行方式？

只是不懂所以问问

**Comment by 7hens** [comment]
OKbinder 的本质上和 aidl 没有什么差别。

目前的基本功能如下：

1. 消息传递是并行的
2. 支持多客户端并用
3. 支持接口回调，并对 List，Map 都提供了支持
4. 支持 oneway，前提是方法的返回值类型必须是 void
5. 不支持 out

**Comment by 7hens** [comment]
@JayceKing 刚刚更新了 OkBinder 的 README，基本功能都写里面了 😁
